# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminMainWindow(object):
    def setupUi(self, AdminMainWindow):
        AdminMainWindow.setObjectName("AdminMainWindow")
        AdminMainWindow.resize(800, 600)
        AdminMainWindow.setMinimumSize(QtCore.QSize(800, 600))
        AdminMainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminMainWindow.setWindowIcon(icon)
        AdminMainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AdminMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(350, 200))
        self.logo.setMaximumSize(QtCore.QSize(350, 200))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../image/游戏大logo.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 1)
        self.menu_Button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menu_Button.sizePolicy().hasHeightForWidth())
        self.menu_Button.setSizePolicy(sizePolicy)
        self.menu_Button.setMinimumSize(QtCore.QSize(201, 31))
        self.menu_Button.setMaximumSize(QtCore.QSize(201, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_Button.setIcon(icon)
        self.menu_Button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.menu_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.menu_Button.setObjectName("menu_Button")

        self.menu_Button.setAutoRaise(True)
        self.menu = QtWidgets.QMenu()

        self.logout = QtWidgets.QAction('注销帐户:', parent=self.menu)
        self.exit_button = QtWidgets.QAction('退出系统', parent=self.menu)

        self.menu.addAction(self.logout)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_button)
        self.menu_Button.setMenu(self.menu)

        self.gridLayout.addWidget(self.menu_Button, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_Frame.setObjectName("main_Frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Button_Frame = QtWidgets.QFrame(self.main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.Button_Frame.sizePolicy().hasHeightForWidth())
        self.Button_Frame.setSizePolicy(sizePolicy)
        self.Button_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Button_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Button_Frame.setObjectName("Button_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Button_Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_Button = QtWidgets.QPushButton(self.Button_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.user_Button.sizePolicy().hasHeightForWidth())
        self.user_Button.setSizePolicy(sizePolicy)
        self.user_Button.setObjectName("user_Button")
        self.horizontalLayout.addWidget(self.user_Button)
        self.game_Button = QtWidgets.QPushButton(self.Button_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.game_Button.sizePolicy().hasHeightForWidth())
        self.game_Button.setSizePolicy(sizePolicy)
        self.game_Button.setObjectName("game_Button")
        self.horizontalLayout.addWidget(self.game_Button)
        self.developer_Button = QtWidgets.QPushButton(self.Button_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.developer_Button.sizePolicy().hasHeightForWidth())
        self.developer_Button.setSizePolicy(sizePolicy)
        self.developer_Button.setObjectName("developer_Button")
        self.horizontalLayout.addWidget(self.developer_Button)
        self.gridLayout_2.addWidget(self.Button_Frame, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.main_Frame, 1, 0, 1, 2)
        AdminMainWindow.setCentralWidget(self.centralwidget)

        self.setWindowOpacity(0.95)  # 设置窗口透明度
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 设置窗口背景透明
        # self.setWindowFlag(QtCore.Qt.FramelessWindowHint)  # 隐藏边框

        self.retranslateUi(AdminMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminMainWindow)

    def retranslateUi(self, AdminMainWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminMainWindow.setWindowTitle(_translate("AdminMainWindow", "Stepic 管理员主界面"))
        self.menu_Button.setText(_translate("AdminMainWindow", "欢迎您，管理员xxx"))
        self.label.setText(_translate("AdminMainWindow", "选择你则您要进行的操作："))
        self.user_Button.setText(_translate("AdminMainWindow", "用户管理"))
        self.game_Button.setText(_translate("AdminMainWindow", "游戏管理"))
        self.developer_Button.setText(_translate("AdminMainWindow", "开发者管理"))
