# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
import json
import datetime
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminUserWindow(object):
    def setupUi(self, AdminUserWindow):
        AdminUserWindow.setObjectName("AdminUserWindow")
        AdminUserWindow.resize(1000, 800)
        AdminUserWindow.setMinimumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminUserWindow.setWindowIcon(icon)
        AdminUserWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        AdminUserWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(AdminUserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(350, 200))
        self.logo.setMaximumSize(QtCore.QSize(350, 200))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../image/游戏大logo.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 1)
        self.user_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.user_table.sizePolicy().hasHeightForWidth())
        self.user_table.setSizePolicy(sizePolicy)
        self.user_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.user_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.user_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.user_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.user_table.setObjectName("user_table")
        self.user_table.setColumnCount(9)
        self.user_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.user_table.setHorizontalHeaderItem(8, item)


        self.gridLayout.addWidget(self.user_table, 1, 0, 1, 2)
        self.menu_Button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.menu_Button.sizePolicy().hasHeightForWidth())
        self.menu_Button.setSizePolicy(sizePolicy)
        self.menu_Button.setMinimumSize(QtCore.QSize(201, 31))
        self.menu_Button.setMaximumSize(QtCore.QSize(201, 31))
        self.menu_Button.setIcon(icon)
        self.menu_Button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.menu_Button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.menu_Button.setObjectName("menu_Button")
        self.gridLayout.addWidget(self.menu_Button, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        AdminUserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminUserWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminUserWindow)

    def retranslateUi(self, AdminUserWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminUserWindow.setWindowTitle(_translate("AdminUserWindow", "Stepic 管理员管理用户界面"))
        item = self.user_table.horizontalHeaderItem(0)
        item.setText(_translate("AdminUserWindow", "用户ID"))
        item = self.user_table.horizontalHeaderItem(1)
        item.setText(_translate("AdminUserWindow", "用户名"))
        item = self.user_table.horizontalHeaderItem(2)
        item.setText(_translate("AdminUserWindow", "用户昵称"))
        item = self.user_table.horizontalHeaderItem(3)
        item.setText(_translate("AdminUserWindow", "用户性别"))
        item = self.user_table.horizontalHeaderItem(4)
        item.setText(_translate("AdminUserWindow", "用户电话"))
        item = self.user_table.horizontalHeaderItem(5)
        item.setText(_translate("AdminUserWindow", "用户生日"))
        item = self.user_table.horizontalHeaderItem(6)
        item.setText(_translate("AdminUserWindow", "经验值"))
        item = self.user_table.horizontalHeaderItem(7)
        item.setText(_translate("AdminUserWindow", "个人简介"))
        item = self.user_table.horizontalHeaderItem(8)
        item.setText(_translate("AdminUserWindow", "操作"))
        self.menu_Button.setText(_translate("AdminUserWindow", "..."))
