# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminLoginWindow(object):
    def setupUi(self, AdminLoginWindow):
        AdminLoginWindow.setObjectName("AdminLoginWindow")
        AdminLoginWindow.setEnabled(True)
        AdminLoginWindow.resize(700, 500)
        AdminLoginWindow.setMinimumSize(QtCore.QSize(700, 500))
        AdminLoginWindow.setMaximumSize(QtCore.QSize(700, 500))
        AdminLoginWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminLoginWindow.setWindowIcon(icon)
        AdminLoginWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AdminLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(60, 20, 351, 161))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../image/游戏大logo.png"))
        self.icon.setObjectName("icon")
        self.adminname = QtWidgets.QLabel(self.centralwidget)
        self.adminname.setGeometry(QtCore.QRect(170, 220, 71, 31))
        self.adminname.setObjectName("adminname")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(170, 280, 71, 31))
        self.password.setObjectName("password")
        self.nametext = QtWidgets.QLineEdit(self.centralwidget)
        self.nametext.setGeometry(QtCore.QRect(270, 220, 251, 31))
        self.nametext.setObjectName("nametext")
        self.passwordtext = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordtext.setGeometry(QtCore.QRect(270, 280, 251, 31))
        self.passwordtext.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordtext.setObjectName("passwordtext")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(270, 330, 91, 21))
        self.checkBox.setObjectName("checkBox")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(180, 420, 93, 28))
        self.loginButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"gridline-color: rgb(85, 0, 0);")
        self.loginButton.setObjectName("loginButton")
        self.exitBottun = QtWidgets.QPushButton(self.centralwidget)
        self.exitBottun.setGeometry(QtCore.QRect(430, 420, 93, 28))
        self.exitBottun.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"color: rgb(85, 0, 0);")
        self.exitBottun.setObjectName("exitBottun")
        self.developer_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.developer_radio.setGeometry(QtCore.QRect(410, 370, 91, 31))
        self.developer_radio.setObjectName("developer_radio")
        self.admin_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.admin_radio.setGeometry(QtCore.QRect(210, 370, 91, 31))
        self.admin_radio.setTabletTracking(False)
        self.admin_radio.setChecked(True)
        self.admin_radio.setObjectName("admin_radio")
        self.developer_regist_button = QtWidgets.QPushButton(self.centralwidget)
        self.developer_regist_button.setGeometry(QtCore.QRect(501, 370, 151, 31))
        self.developer_regist_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.developer_regist_button.setObjectName("developer_regist_button")
        AdminLoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminLoginWindow)

    def retranslateUi(self, AdminLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminLoginWindow.setWindowTitle(_translate("AdminLoginWindow", "Stepic 管理员登录"))
        self.adminname.setText(_translate("AdminLoginWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600;\">账户：</span></p></body></html>"))
        self.password.setText(_translate("AdminLoginWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600;\">密码：</span></p></body></html>"))
        self.checkBox.setText(_translate("AdminLoginWindow", "记住密码"))
        self.loginButton.setText(_translate("AdminLoginWindow", "登录"))
        self.exitBottun.setText(_translate("AdminLoginWindow", "取消"))
        self.developer_radio.setText(_translate("AdminLoginWindow", "开发者"))
        self.admin_radio.setText(_translate("AdminLoginWindow", "管理员"))
        self.developer_regist_button.setText(_translate("AdminLoginWindow", "注册一个开发者账号"))
