# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserRegist.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserRegistWindow(object):
    def setupUi(self, UserRegistWindow):
        UserRegistWindow.setObjectName("UserRegistWindow")
        UserRegistWindow.resize(614, 384)
        UserRegistWindow.setMinimumSize(QtCore.QSize(614, 384))
        UserRegistWindow.setMaximumSize(QtCore.QSize(614, 384))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/游戏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserRegistWindow.setWindowIcon(icon)
        UserRegistWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(UserRegistWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_icon = QtWidgets.QLabel(self.centralwidget)
        self.label_icon.setGeometry(QtCore.QRect(80, 10, 231, 91))
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap("../image/游戏大logo-s.png"))
        self.label_icon.setObjectName("label_icon")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(90, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(180, 120, 361, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_pwd = QtWidgets.QLabel(self.centralwidget)
        self.label_pwd.setGeometry(QtCore.QRect(120, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_pwd.setFont(font)
        self.label_pwd.setObjectName("label_pwd")
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(180, 170, 361, 31))
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.btn_regist = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regist.setGeometry(QtCore.QRect(180, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_regist.setFont(font)
        self.btn_regist.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_regist.setAutoDefault(False)
        self.btn_regist.setDefault(False)
        self.btn_regist.setFlat(False)
        self.btn_regist.setObjectName("btn_regist")
        self.btn_close = QtWidgets.QToolButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(360, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_close.setObjectName("btn_close")
        self.label_repwd = QtWidgets.QLabel(self.centralwidget)
        self.label_repwd.setGeometry(QtCore.QRect(90, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_repwd.setFont(font)
        self.label_repwd.setObjectName("label_repwd")
        self.lineEdit_repwd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_repwd.setGeometry(QtCore.QRect(180, 220, 361, 31))
        self.lineEdit_repwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_repwd.setObjectName("lineEdit_repwd")
        UserRegistWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserRegistWindow)
        QtCore.QMetaObject.connectSlotsByName(UserRegistWindow)

    def retranslateUi(self, UserRegistWindow):
        _translate = QtCore.QCoreApplication.translate
        UserRegistWindow.setWindowTitle(_translate("UserRegistWindow", "Stepic 注册"))
        self.label_name.setText(_translate("UserRegistWindow", "账户名称"))
        self.label_pwd.setText(_translate("UserRegistWindow", " 密码"))
        self.btn_regist.setText(_translate("UserRegistWindow", "注册"))
        self.btn_close.setText(_translate("UserRegistWindow", "取消"))
        self.label_repwd.setText(_translate("UserRegistWindow", "确认密码"))
